apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-app2-a
  labels:
    app: external-app2-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-app2-a
  template:
    metadata:
      name: external-app2-a
      labels:
        app: external-app2-a
    spec:
      containers:
        - name: external-app2-a
          image: eggboy/echo-app:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: APP_NAME
              value: "External Subdomain2 with patha"
      restartPolicy: Always
