apiVersion: v1
kind: Service
metadata:
  name: workloadidentity-blob
spec:
  selector:
    app: workloadidentity-blob
  ports:
    - port: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: workloadidentity-blob
  labels:
    app: workloadidentity-blob
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - name: workloadidentity-blob
      image: eggboy/workloadidentity-blob:0.0.1
      imagePullPolicy: Always
      env:
        - name: BLOB_ACCOUNT_NAME
          value: ""
        - name: BLOB_CONTAINER_NAME
          value: ""
  restartPolicy: Always
