on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  
jobs:
  kubelogin:
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./GithubAction/kubelogin.yml
