name: 'kubelogin'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  kubelogin:
    name: 'kubelogin'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    env:
      AAD_SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.AAD_SERVICE_PRINCIPAL_CLIENT_ID }}
      AAD_SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.AAD_SERVICE_PRINCIPAL_CLIENT_SECRET }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
#    - name: Install Azure cli
#      run: |
#        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
#        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
#        AZ_REPO=$(lsb_release -cs)
#        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
#        sudo apt-get update
#        sudo apt-get install azure-cli
    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
    - uses: azure/setup-kubectl@v3
      name: Setup kubectl
    - name: Setup kubelogin
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.26'
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: 'sandbox-rg'
        cluster-name: 'rbac-cluster'
        admin: 'false'
        use-kubelogin: 'true'
    - name: Run kubectl
      run: |
        kubectl get pods
